### ISSUE TITLE
fails on go 1.6

### ISSUE THREAD

**Issue by hxw** [tvdburgt/go-argon2#1]
go 1.6 has restrictions on pointer passing to C:

From: https://tip.golang.org/cmd/cgo/#hdr-Passing_pointers
> Go code may pass a Go pointer to C provided the Go memory to which it points does not contain any Go pointers. 

This results in the failure:
```
panic: runtime error: cgo argument has Go pointer to Go pointer
```

I have created a fork, https://github.com/bitmark-inc/go-argon2 to solve this problem.
However, I also removed git submodule and link to the shared version of the libargon2 using a more recent version with changed API (some functions and parameters were changed).

The main fix is to add `wrapper.h` that is used to pass all pointers as function parameter, create, use and destroy the C struct inside the wrapper so that the Go Garbage Collector can track them correctly.
Also this for is for FreeBSD.

**Comment by Foorack** [comment]
Can confirm this bug. Getting the same error.

**Comment by tvdburgt** [comment]
Thanks for creating this issue. I merged the changes from your fork and some other improvements to master.
