### ISSUE TITLE
Compatibility with golang.org/x/crypto/argon2 ?

### ISSUE THREAD

**Issue by tbruyelle** [tvdburgt/go-argon2#10]
Hi @tvdburgt,

I'm comparing your library and a new one integrated in `golang.org/x/crypto/argon2`, and I'm disappointed by the result of my tests. 

With the same salt, password and params, I don't get the same hash, it's really weird isn't it ? 

Am I missing something ?

To demonstrate, please consider the following test, that fails when I run it at the root of your library : 

```go
package argon2

import (
	"bytes"
	"encoding/base64"
	"testing"

	xargon2 "golang.org/x/crypto/argon2"
)

func TestCompat(t *testing.T) {
	salt := []byte("0123456789abcdef")
	pwd := []byte("some password")

	ctx := &Context{
		Iterations:  3,
		Memory:      1 << 16,
		Parallelism: 4,
		HashLen:     32,
		Mode:        ModeArgon2i,
	}
	hash, err := Hash(ctx, pwd, salt)
	if err != nil {
		t.Fatal(err)
	}

	xhash := xargon2.Key(pwd, salt, 3, 1<<16, 4, 32)

	if !bytes.Equal(hash, xhash) {
		t.Errorf("Compat failed:\n%s\n%s\n",
			base64.StdEncoding.EncodeToString(hash),
			base64.StdEncoding.EncodeToString(xhash),
		)
	}
}
```

```sh
$ go test .
--- FAIL: TestCompat (0.08s)
    compat_test.go:30: Compat failed:
        UgjfozCx6kU6vTNKoN8Ic2UTh7Ckphy0Dc79+1xlT/0=
        mf9LVGs+VH62cWpoLZVfCvtBWye6uMD7sWJfhYQk3fo=
FAIL
FAIL	github.com/tvdburgt/go-argon2	0.362s
```

Any help would be appreciated, thanks in advance!

**Comment by tbruyelle** [comment]
Ok someone found the problem, it's because the default version is not `Version13`.

If I set `Version13`, the hashes are the same.

**Comment by matm** [comment]
Nice catch @tbruyelle. Would have been easier to debug if the version `$v=13$` was part of the final hash...

**Comment by tvdburgt** [comment]
I didn't knew about `golang.org/x/crypto/argon2`! I updated the Hash function to ensure the version defaults to `ARGON2_VERSION_NUMBER` (which is currently `ARGON2_VERSION_13`).

Thank you for submitting the issue.
