### ISSUE TITLE
Running on Windows is impossible

### ISSUE THREAD

**Issue by pzduniak** [tvdburgt/go-argon2#5]
Hi, the last time I tried to run go-argon2 on Windows I ended up porting the C code to pure Go. 2 versions have been released since that time and yet again I'm in need of a Go argon2 lib. Unfortunately I am not able to run the bindings without any changes on Windows - most of the issues are related to paths etc.

I "backported" (doesn't really make sense in this context, eh) the way the lib was included ~1yr ago and it works without any issues. [Here's the code](https://github.com/pzduniak/go-argon2). This is also how mattn's go-sqlite3 works. Are you sure that the current usage method is the best way? Maybe the previous setup was better?

**Comment by tvdburgt** [comment]
I haven't managed to get argon2 working on Windows. A pure Go library is now available you could try: `golang.org/x/crypto/argon2`.

**Comment by pzduniak** [comment]
Thanks for the notification, it's great to know, I can finally kill off some of my argon2 repos :)
