### ISSUE TITLE
Building with path of argon2

### ISSUE THREAD

**Issue by mimoo** [tvdburgt/go-argon2#6]
Hoy hoy, is there a way not to have to `make install` argon2 (so that it gets into `/usr`), but just provide the path to the library?

I'm guessing the best way right now is to modify these:

```go
// #cgo CFLAGS: -I/usr/include
// #cgo LDFLAGS: -L/usr/lib -largon2
```

in `$GOPATH/src/github.com/tvdburgt/go-argon2/*.go`

but then I get this error when trying to run `go test` in the library:

```sh
dyld: Library not loaded: @rpath/libargon2.dylib
  Referenced from: /var/folders/hh/2pwh6hxj7_vf8v89n2s74j2m0000gn/T/go-build726324610/github.com/tvdburgt/go-argon2/_test/go-argon2.test
  Reason: image not found
signal: abort trap
FAIL    github.com/tvdburgt/go-argon2   0.004s
```

(I'm on MAC)

PS: I suggest you add this to the README for easy copy/pasting 😛:

```go
import "github.com/tvdburgt/go-argon2"
```

**Comment by tvdburgt** [comment]
Theoretically this should work, but haven't tried it myself. It seems your library path doesn't contain the right libargon2 object files.
