### ISSUE TITLE
unimplemented: 64-bit mode not compiled 

### ISSUE THREAD

**Issue by 5-digits** [tvdburgt/go-argon2#9]
Hi,
i installed the minGW and download all packages and when i'm trying using this go Repository, I found this problem 

`cc1.exe: sorry, unimplemented: 64-bit mode not compiled in`

So how to fix that

**Comment by tvdburgt** [comment]
Do you get this when `make`ing argon2? Make sure your compiler supports 64-bit. Haven't really tried this library on Windows or with MinGW, so can't help you there...
